### ISSUE TITLE
type 'List<dynamic>' is not a subtype of type 'List<int>' in type cast

### ISSUE THREAD

**Issue by mdev88** [ERP-Ukraine/odoo-rpc-dart#10]
Hello.

I'm getting this exception when authenticating with the server. I just upgraded to Flutter 2 in stable and I am tracking and fixing some issues here and there. This code used to work just fine, but now I get this exception. What can be causing this...?

I am using odoo_rpc 0.4.0

Thanks

```
 [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<int>' in type cast
 #0      OdooSession.fromSessionInfo (package:odoo_rpc/src/odoo_session.dart:58:49)
 #1      OdooClient.authenticate (package:odoo_rpc/src/odoo_client.dart:253:32)
 <asynchronous suspension>
 #2      APIService.initialize (package:nbp_odoo_client/app/services/API_service.dart:32:13)
 <asynchronous suspension>
 #3      _LoginPageState.loginAction (package:nbp_odoo_client/app/pages/login_page.dart:169:30)
 <asynchronous suspension>
```

**Comment by lem8r** [comment]
Hi!

Thanks for reporting.

Please use version ^0.4.2
