### ISSUE TITLE
error OdooException: {code: 200, message: Odoo Server Error, data: {name: builtins.ValueError, debug: Traceback (most recent call last):

### ISSUE THREAD

**Issue by abdallahi34** [ERP-Ukraine/odoo-rpc-dart#43]
when i try this code :
var res = await client.callKw({
          'model': 'hr.attendance',
          'method': 'write',
          'args': [
            17,
            {
              'check_out': a,
            },
          ],
          'kwargs': {},
        }); 
 I have this error:
  error OdooException: {code: 200, message: Odoo Server Error, data: {name: builtins.ValueError, debug: Traceback (most recent call last):
I/flutter ( 5416):   File "/home/odoo/src/odoo/saas-16.4/odoo/http.py", line 1710, in _serve_db
I/flutter ( 5416):     return service_model.retrying(self._serve_ir_http, self.env)
I/flutter ( 5416):   File "/home/odoo/src/odoo/saas-16.4/odoo/service/model.py", line 133, in retrying
I/flutter ( 5416):     result = func()
I/flutter ( 5416):   File "/home/odoo/src/odoo/saas-16.4/odoo/http.py", line 1737, in _serve_ir_http
I/flutter ( 5416):     response = self.dispatcher.dispatch(rule.endpoint, args)
I/flutter ( 5416):   File "/home/odoo/src/odoo/saas-16.4/odoo/http.py", line 1938, in dispatch
 result = self.request.registry['ir.http']._dispatch(endpoint)
I/flutter ( 5416):   File "/home/odoo/src/odoo/saas-16.4/addons/website/models/ir_http.py", line 233, in _dispatch
I/flutter ( 5416):     response = super()._dispatch(endpoint)
I/flutter ( 5416):   File "/home/odoo/src/odoo/saas-16.4/odoo/addons/base/models/ir_http.py", line 191, in _dispatch
I/flutter ( 5416):     result = endpoint(**request.params)
I/flutter ( 5416):   File "/home/odoo/src/odoo/saas-16.4/odoo/http.py", line 717, in route_wrappe

how to resolve it

**Comment by lem8r** [comment]
Hi!
Try the most recent version 0.5.4. There are few bugs fixed there.
