### ISSUE TITLE
Incomplete text in exceptions

### ISSUE THREAD

**Issue by mdev88** [ERP-Ukraine/odoo-rpc-dart#9]
Hello,

Whenever I get an exception, the full stacktrace is incomplete. For example: 

```
OdooException: {code: 200, message: Odoo Server Error, data: {name: psycopg2.DataError, debug: Traceback (most recent call last):
   File "/opt/odoo/odoo/http.py", line 624, in _handle_exception
     return super(JsonRequest, self)._handle_exception(exception)
   File "/opt/odoo/odoo/http.py", line 310, in _handle_exception
     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
   File "/opt/odoo/odoo/tools/pycompat.py", line 14, in reraise
     raise value
   File "/opt/odoo/odoo/http.py", line 669, in dispatch
     result = self._call_function(**self.params)
   File "/opt/odoo/odoo/http.py", line 350, in _call_function
     return checked_call(self.db, *args, **kwargs)
   File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
     return f(dbname, *args, **kwargs)
   File "/opt/odoo/odoo/http.py", line 339, in checked_call
     result = self.endpoint(*a, **kw)
   File "/opt/odoo/odoo/http.py", line 915, in __call__
     return self.method(*args, **kw)
   File "/opt/odoo/odoo/http.py", line 515, in
```

I'm not sure if this is due to something in odoo-rpc-dart or somewhere else. Any ideas how may I fix this?

Thanks

**Comment by lem8r** [comment]
There is no limitation to message length on `OdooException` side. It contains everything that is received.
Maybe you have logger limit.

**Comment by mdev88** [comment]
It's weird because even if I run the app on a linux terminal the output in these exceptions is always incomplete. I don't have another target to test (python or Odoo) to see if it's specific to this server or if it happens everywhere.
